/**
 * Worker entrypoint - the Next.js app plus operational sync crons.
 *
 * OpenNext generates `.open-next/worker.js` with a `fetch` handler and nothing
 * else, so a scheduled handler has to live in a wrapper that re-uses it. That
 * is all this file is: wrangler's `main` points here instead of at the generated
 * worker, and the Next.js side is untouched.
 *
 * Monday's billing job captures the exact just-closed Google week and then
 * reconciles Stripe payment state. It can never create or issue an invoice;
 * issuing requires an admin confirmation through /api/billing/generate.
 *
 * `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and is
 * gitignored, so whether TypeScript can resolve it depends on whether a build
 * has run. That is exactly what ts-ignore is for here — ts-expect-error would
 * itself error on the machines where the file DOES exist.
 */

/* eslint-disable @typescript-eslint/ban-ts-comment -- see above */

// @ts-ignore — generated at build time.
import { default as handler } from "./.open-next/worker.js";

// Durable Objects the adapter may register for the queue and tag caches. They
// must be re-exported from the entrypoint or their bindings stop resolving.
// @ts-ignore — generated at build time.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

/* eslint-enable @typescript-eslint/ban-ts-comment */

/** Only what this file touches — the repo has no @cloudflare/workers-types. */
type Env = {
  CRON_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
};

type Ctx = { waitUntil(promise: Promise<unknown>): void };

const nextHandler = handler as {
  fetch(request: Request, env: Env, ctx: Ctx): Promise<Response>;
};

const TEMPORARY_LARA_TRUST_PAGES_CRON = "*/2 * * * *";
const LARA_TRUST_PAGES_PATH = "/api/internal/audit/lara/trust-pages";
const LARA_TRUST_PAGES_CONFIRMATION = JSON.stringify({
  action: "apply",
  confirmation: "apply-lara-contact-about-approved-copy",
});

const worker = {
  fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> {
    return nextHandler.fetch(request, env, ctx);
  },

  async scheduled(event: { cron: string }, env: Env, ctx: Ctx): Promise<void> {
    if (!env.CRON_SECRET) {
      console.error("Cron skipped: CRON_SECRET is not set on this Worker.");
      return;
    }

    // Only the path is ever used for routing; the origin just has to be a valid
    // absolute URL, so a missing site URL must not abort the run.
    const origin = env.NEXT_PUBLIC_SITE_URL ?? "https://dropscale.app";

    /**
     * TEMPORARY FIXED REPAIR: replace only the body of Lara's two exact trust
     * pages with the approved merchant identity. The route owns the shop,
     * page ids, full HTML, plan digest and stable run id. Repeated ticks only
     * resume or re-verify that fenced one-shot run. Remove this branch and its
     * matching trigger immediately after Admin and storefront verification.
     */
    if (event.cron === TEMPORARY_LARA_TRUST_PAGES_CRON) {
      try {
        const response = await nextHandler.fetch(
          new Request(`${origin}${LARA_TRUST_PAGES_PATH}`, {
            method: "POST",
            headers: {
              Authorization: `Bearer ${env.CRON_SECRET}`,
              "Content-Type": "application/json",
            },
            body: LARA_TRUST_PAGES_CONFIRMATION,
          }),
          env,
          ctx,
        );

        const body = await response.text();
        if (!response.ok) {
          console.error(
            `Cron "temporary Lara trust pages" ${LARA_TRUST_PAGES_PATH} failed (${response.status}): ${body}`,
          );
          return;
        }
        console.log(
          `Cron "temporary Lara trust pages" ${LARA_TRUST_PAGES_PATH}: ${body}`,
        );
      } catch (error) {
        console.error(
          `Cron "temporary Lara trust pages" ${LARA_TRUST_PAGES_PATH} threw:`,
          error,
        );
      }
      return;
    }

    /**
     * Which schedule fired decides the work. Every route is idempotent, so a
     * retried or double-fired trigger costs nothing but a round trip.
     *
     * The hourly tick runs BOTH syncs, in order: the metrics rollup is what
     * the client reports read, and the ledger is what the finance pages read.
     * Refreshing only the ledger — as this used to — left the reports showing
     * whatever the last page view happened to capture, which is exactly the
     * staleness the countdown in the report now promises is bounded.
     */
    const job: { name: string; paths: string[] } =
      event.cron === "5 14 * * 1"
        ? {
            name: "weekly billing evidence and invoice reconciliation",
            paths: [
              "/api/admin/sync-ledgers?billingWeek=latest",
              "/api/billing/cron",
            ],
          }
        : event.cron === "55 23 * * *"
          ? {
              name: "daily close",
              paths: ["/api/admin/sync-metrics", "/api/billing/cron"],
            }
          : {
              name: "hourly refresh",
              paths: ["/api/admin/sync-metrics", "/api/admin/sync-ledgers"],
            };

    // Sequential, not parallel: the ledger reads Google, the rollup writes it,
    // and two concurrent syncs would only race each other for the same quota.
    for (const path of job.paths) {
      try {
        const response = await nextHandler.fetch(
          new Request(`${origin}${path}`, {
            method: "POST",
            headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
          }),
          env,
          ctx,
        );

        const body = await response.text();
        if (!response.ok) {
          console.error(`Cron "${job.name}" ${path} failed (${response.status}): ${body}`);
          continue; // One failing leg must not skip the other.
        }
        console.log(`Cron "${job.name}" ${path}: ${body}`);
      } catch (error) {
        console.error(`Cron "${job.name}" ${path} threw:`, error);
      }
    }
  },
};

export default worker;
