/**
 * Worker entrypoint — the Next.js app plus a cron.
 *
 * OpenNext generates `.open-next/worker.js` with a `fetch` handler and nothing
 * else, so a scheduled handler has to live in a wrapper that re-uses it. That
 * is all this file is: wrangler's `main` points here instead of at the generated
 * worker, and the Next.js side is untouched.
 *
 * Every Monday (see `triggers.crons` in wrangler.jsonc) we bill the week that
 * just closed. Rather than fetch our own public URL — an egress round trip, and
 * one that would break the moment DNS or the hostname changed — we call the
 * generated fetch handler directly with a request we build in memory. Next.js
 * routes it to /api/billing/cron exactly as if it had arrived over the wire,
 * which is also why that route still checks the bearer secret: it is publicly
 * reachable and cannot tell the difference.
 *
 * `.open-next/worker.js` is generated by `opennextjs-cloudflare build` and is
 * gitignored, so whether TypeScript can resolve it depends on whether a build
 * has run. That is exactly what ts-ignore is for here — ts-expect-error would
 * itself error on the machines where the file DOES exist.
 */

/* eslint-disable @typescript-eslint/ban-ts-comment -- see above */

// @ts-ignore — generated at build time.
import { default as handler } from "./.open-next/worker.js";

// Durable Objects the adapter may register for the queue and tag caches. They
// must be re-exported from the entrypoint or their bindings stop resolving.
// @ts-ignore — generated at build time.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

/* eslint-enable @typescript-eslint/ban-ts-comment */

/** Only what this file touches — the repo has no @cloudflare/workers-types. */
type Env = {
  CRON_SECRET?: string;
  NEXT_PUBLIC_SITE_URL?: string;
};

type Ctx = { waitUntil(promise: Promise<unknown>): void };

const nextHandler = handler as {
  fetch(request: Request, env: Env, ctx: Ctx): Promise<Response>;
};

const worker = {
  fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> {
    return nextHandler.fetch(request, env, ctx);
  },

  async scheduled(_event: { cron: string }, env: Env, ctx: Ctx): Promise<void> {
    if (!env.CRON_SECRET) {
      console.error("Billing cron skipped: CRON_SECRET is not set on this Worker.");
      return;
    }

    // Only the path is ever used for routing; the origin just has to be a valid
    // absolute URL, so a missing site URL must not abort the run.
    const origin = env.NEXT_PUBLIC_SITE_URL ?? "https://dropscale.app";

    try {
      const response = await nextHandler.fetch(
        new Request(`${origin}/api/billing/cron`, {
          method: "POST",
          headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
        }),
        env,
        ctx,
      );

      const body = await response.text();
      if (!response.ok) {
        console.error(`Billing cron failed (${response.status}): ${body}`);
        return;
      }
      console.log(`Billing cron: ${body}`);
    } catch (error) {
      console.error("Billing cron threw:", error);
    }
  },
};

export default worker;
