import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Cloudflare/OpenNext build — not ours to lint.
    ".open-next/**",
    ".wrangler/**",
    // The research tool is vendored verbatim from the trends-radar project so
    // its validated chart and comparison logic stays byte-identical. Linting a
    // copy we do not author would only invite drift.
    "public/research/**",
  ]),
]);

export default eslintConfig;
